.test_image:
  script:
    - docker build -f ${DOCKERFILE} -t $REPOSITORY/$IMAGE_NAME $BUILD_DIR
  only:
    - merge_requests

.push_image:
  script:
    - $(aws ecr get-login --no-include-email --region eu-west-1)
    - docker build -f ${DOCKERFILE} -t $REPOSITORY/$IMAGE_NAME:$IMAGE_TAG $BUILD_DIR
    - docker push $REPOSITORY/$IMAGE_NAME:$IMAGE_TAG