before_script:
  - docker login -u ${CI_REGISTRY_USER} -p ${CI_JOB_TOKEN} ${CI_REGISTRY}

.docker_test:
  script:
    - docker build --build-arg ${CI_JOB_TOKEN} -t ${CI_REGISTRY_IMAGE} .
  only:
    - merge_requests

.docker_push:
  script:
    - docker build --build-arg ${CI_JOB_TOKEN} -t ${CI_REGISTRY_IMAGE} -t ${CI_REGISTRY_IMAGE}:${DOCKER_TAG} .
    - docker push ${CI_REGISTRY_IMAGE}
    - docker push ${CI_REGISTRY_IMAGE}:${DOCKER_TAG}
  only:
    - tags
