before_script:
  - docker login -u ${CI_REGISTRY_USER} -p ${CI_JOB_TOKEN} ${CI_REGISTRY}

.docker_test:
  variables:
    DOCKER_ADDITIONAL_ARGUMENTS: ""
  script:
    - docker build --build-arg ${CI_JOB_TOKEN} ${DOCKER_ADDITIONAL_ARGUMENTS} -t ${CI_REGISTRY_IMAGE} .
  only:
    - merge_requests
  tags:
    - app
    - docker_runner

.docker_push:
  variables:
    DOCKER_ADDITIONAL_ARGUMENTS: ""
  script:
    - docker build --build-arg ${CI_JOB_TOKEN} ${DOCKER_ADDITIONAL_ARGUMENTS} -t ${CI_REGISTRY_IMAGE} -t ${CI_REGISTRY_IMAGE}:${DOCKER_TAG} .
    - docker push ${CI_REGISTRY_IMAGE}
    - docker push ${CI_REGISTRY_IMAGE}:${DOCKER_TAG}
  only:
    - tags
  tags:
    - app
    - docker_runner

