before_script:
  - docker login -u ${CI_REGISTRY_USER} -p ${CI_JOB_TOKEN} ${CI_REGISTRY}

.test_image:
  script:
    - docker build -f ${DOCKERFILE} -t ${CI_REGISTRY_IMAGE} $BUILD_DIR
  only:
    - merge_requests

.push_image:
  script:
    - docker build -f ${DOCKERFILE} -t ${CI_REGISTRY_IMAGE}:${DOCKER_TAG} --build-arg PIPELINE_ID=${PIPELINE_ID} $BUILD_DIR
    - docker push ${CI_REGISTRY_IMAGE}:${DOCKER_TAG}
