include:
  - project: 'DashDevs/PFM/infrastructure/shared-pipelines'
    ref: master
    file: '/docker/steps.yml'
stages: 
  - test
  - integration_test
  - build
  - deploy_dev
  - deploy_stage
  - rollback
image: registry.gitlab.com/dashdevs/pfm/infrastructure/docker-images/gitlab-ci:build-deploy  
.template: &ireland-runner
  tags: 
    - docker_runner_ireland
  before_script:
    - export IMAGE_TAG="${CI_COMMIT_SHORT_SHA}"
    - echo "Image tag is="$IMAGE_TAG  
'Test code':
  except: 
    - master
  stage: test
  extends: .test_code
  <<: *ireland-runner
'Test code integration':
  except: 
    - master
  stage: integration_test
  extends: .integration_test
  <<: *ireland-runner  
'Build containers':
  only:
    - master
  stage: build
  extends: .build_image
  variables:
    IMAGE_NAME: "pfm/obpexporter.service"
  <<: *ireland-runner 
'DEV Deploy containers':
  only: 
    - master
  stage: deploy_dev
  extends: .deploy_dev
  variables:
    SERVICE_NAME: obp-exporter-service
  <<: *ireland-runner        
'STAGE Deploy containers':
  only:
    - master
  stage: deploy_stage
  extends: .deploy_stage
  variables:
    ENV_NAME: Staging
    SERVICE_NAME: obp-exporter-service
  <<: *ireland-runner  
  when: manual
'Rollback to previous state dev':
  stage: rollback
  extends: .rollback_dev
  variables:
    SERVICE_NAME: obp-exporter-service
  when: manual
  <<: *ireland-runner  
'Rollback to previous state stage':
  stage: rollback
  extends: .rollback_stage
  variables:
    SERVICE_NAME: obp-exporter-service
  when: manual
  <<: *ireland-runner
