.deploy:
  script:
    - helm upgrade $SERVICE_NAME ${HELM_PATH} -f ${HELM_VALUES} --set image.repository=$CI_REGISTRY_IMAGE --set image.tag=$DOCKER_TAG  --set environment=$ENV_NAME --set base_url=$BASE_URL --namespace $NAMESPACE --install

.rollback_dev:
  script:
    - echo ${ENV_NAME}
    - helm rollback $SERVICE_NAME 0 --namespace dev

.rollback_stage:
  script:
    - echo ${ENV_NAME}
    - helm rollback $SERVICE_NAME 0 --namespace stage

.rollback:
  script:
  - echo ${ENV_NAME}
  - helm rollback $SERVICE_NAME 0 --namespace ${NAMESPACE}